import {readFile,writeFile} from 'node:fs/promises';
import {profile,projects,experience,skills} from '../content/profile.mjs';
const e = v => String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tags = values => `<div class="tech-badges">${values.map(v=>`<span class="tech-badge">${e(v)}</span>`).join('')}</div>`;
const bullets = values => `<ul class="cv-bullets">${values.map(v=>`<li>${e(v)}</li>`).join('')}</ul>`;
const section = (id,label,title,body,alt=false) => `<section class="section-pad ${alt?'section-alt':''}" id="${id}"><div class="container"><div class="section-header reveal-up"><p class="section-label">${label}</p><h2 class="section-title">My <span class="gradient-text">${title}</span></h2></div>${body}</div></section>`;
const timeline = (date,title,org,body,icon='fa-code') => `<div class="timeline-item reveal-up"><div class="timeline-dot"><i class="fas ${icon}" aria-hidden="true"></i></div><div class="timeline-card"><div class="timeline-date">${e(date)}</div><h4>${e(title)}</h4><h5>${e(org)}</h5>${body}</div></div>`;
const replacements={
 SUMMARY:`<p>${e(profile.summary)}</p><div class="about-tags d-flex flex-wrap gap-2 mt-3"><span class="tag">Clean Architecture</span><span class="tag">CQRS</span><span class="tag">SOLID</span><span class="tag">Team Collaboration</span></div>`,
 CV_LINK:profile.cvUrl?`<a href="${e(profile.cvUrl)}" download class="btn btn-ghost-custom">Download CV</a>`:'',
 EDUCATION:section('education','Academic Background','Education',`<div class="timeline mt-5">${timeline('2024 — 2028 (Expected)','Bachelor of Computer Science','Zagazig University','<p>Computer Science student developing practical experience through backend and full-stack team projects.</p>','fa-graduation-cap')}${timeline('Jun 2026','McKinsey.org Forward Program','Professional Development','<p>Professional development program focused on structured problem solving, communication, adaptability, teamwork, and digital & AI fundamentals.</p>','fa-briefcase')}</div>`,true),
 EXPERIENCE:section('experience','My Journey','Experience',`<div class="timeline mt-5">${experience.map(x=>timeline(x.date,x.title,x.organization,bullets(x.details))).join('')}</div>`),
 SKILLS:section('skills','What I Work With','Skills',`<div class="row g-4 mt-4">${skills.map(([n,title,items])=>`<div class="col-md-6 col-lg-4 reveal-up"><div class="skill-card skill-category"><div class="skill-icon"><i class="fas ${['fa-code','fa-layer-group','fa-database','fa-sitemap','fa-desktop','fa-tools'][Number(n)-1]}" aria-hidden="true"></i></div><h3>${e(title)}</h3>${tags(items)}</div></div>`).join('')}</div>`,true),
 PROJECTS:section('projects','What I Have Built','Projects',`<div class="project-filters d-flex justify-content-center gap-2 flex-wrap mt-4 mb-4" role="group" aria-label="Filter projects">${[['all','All Projects'],['backend','Backend'],['fullstack','Full Stack'],['frontend','Frontend']].map(([v,l])=>`<button class="filter-btn ${v==='all'?'active':''}" data-filter="${v}" aria-pressed="${v==='all'}">${l}</button>`).join('')}</div><p id="project-count" class="visually-hidden" role="status">Showing 3 projects</p><div class="row g-4">${projects.map((p,i)=>`<div class="col-lg-4 col-md-6 project-item reveal-up" data-category="${p.category}"><article class="project-card"><div class="project-visual visual-${p.id}" aria-hidden="true"><div class="visual-grid"></div><i class="fas ${['fa-server','fa-university','fa-laptop-code'][i]}"></i><span>${e(p.name)}</span><small>${['ASP.NET CORE / EF CORE','PHP / MYSQL','HTML / CSS / TYPESCRIPT'][i]}</small></div><div class="project-body"><p class="project-role">${e(p.role)}</p><h3 class="project-title">${e(p.name)}</h3><p class="project-desc">${e(p.description)}</p>${tags(p.tags)}<details class="project-details"><summary>My contribution</summary>${bullets(p.details)}</details><div class="project-links">${p.links.map(([label,url])=>`<a href="${e(url)}" target="_blank" rel="noopener noreferrer">${e(label)} <i class="fas fa-arrow-up-right-from-square" aria-hidden="true"></i></a>`).join('')}</div></div></article></div>`).join('')}</div>`),
 SERVICES:section('services','How I Apply My Skills','Focus',`<div class="row g-4 mt-4">${[['fa-server','Backend Development','RESTful APIs, authentication and authorization with ASP.NET Core, EF Core, and JWT.'],['fa-database','Database-Driven Applications','Relational data and persistence with SQL Server, MySQL, Entity Framework Core, and ADO.NET.'],['fa-laptop-code','Full-Stack Development','Responsive interfaces and PHP/Laravel applications, applying MVC and OOP concepts.']].map(([icon,title,body])=>`<div class="col-md-4 reveal-up"><div class="service-card"><div class="service-icon-wrap"><i class="fas ${icon}" aria-hidden="true"></i></div><h4>${title}</h4><p>${body}</p></div></div>`).join('')}</div>`),
 SHAPES:`<div class="shape-field" aria-hidden="true"><div class="cube-anchor"><div class="cube">${['front','back','left','right','top','bottom'].map(face=>`<span class="cube-face ${face}"></span>`).join('')}</div></div><div class="orbit orbit-a"></div><div class="orbit orbit-b"></div><div class="glass-sphere"></div><span class="floating-tech tech-a">&lt;/&gt; C#</span><span class="floating-tech tech-b">SQL</span><span class="floating-tech tech-c">.NET</span></div>`
};
let html=await readFile(new URL('../templates/index.html',import.meta.url),'utf8');
for(const [key,value] of Object.entries(replacements)) html=html.replace(`{{${key}}}`,value);
if(/\{\{[A-Z_]+\}\}/.test(html)) throw new Error('Unresolved template placeholder');
await writeFile(new URL('../index.html',import.meta.url),html.replace(/[ \t]+$/gm,''));
console.log('Built original blue portfolio with current CV content.');
